namespace Dwarf.Toolkit.Tests.SourceGenerators;

using Dwarf.Toolkit.Maui.SourceGenerators;
using NUnit.Framework;
using static CodegenTestHelpers;

[TestFixture]
internal sealed class AttachedPropertyTest
{
	[TestCase]
	public void SimpleAttachedProperty()
	{
		var source = """
			using Microsoft.Maui.Controls;
			using Dwarf.Toolkit.Maui;

			namespace SimpleAttachedProps;

			static partial class Container
			{
				[AttachedProperty]
				public static partial string? GetTextSample(Label target);
				[AttachedProperty]
				internal static partial int? GetNumSample(BindableObject target);
				[AttachedProperty]
				static partial object? GetPrivateObject(BindableObject target);
			}
			""";

		var result = """
			// <auto-generated/>
			#pragma warning disable
			#nullable enable
			namespace SimpleAttachedProps;
			/// <inheritdoc/>
			partial class Container
			{
				/// <summary>
				/// Creates an attached property named TextSample, of type <see cref="string"/>
				/// </summary>
				public static readonly global::Microsoft.Maui.Controls.BindableProperty TextSampleProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("TextSample", typeof(string), typeof(Container), default);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public static partial string? GetTextSample(global::Microsoft.Maui.Controls.Label target) => (string)target.GetValue(TextSampleProperty);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public static void SetTextSample(global::Microsoft.Maui.Controls.Label target, string? value) => target.SetValue(TextSampleProperty, value);
				/// <summary>
				/// Creates an attached property named NumSample, of type <see cref="int?"/>
				/// </summary>
				public static readonly global::Microsoft.Maui.Controls.BindableProperty NumSampleProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("NumSample", typeof(int?), typeof(Container), default);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal static partial int? GetNumSample(global::Microsoft.Maui.Controls.BindableObject target) => (int?)target.GetValue(NumSampleProperty);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal static void SetNumSample(global::Microsoft.Maui.Controls.BindableObject target, int? value) => target.SetValue(NumSampleProperty, value);
				/// <summary>
				/// Creates an attached property named PrivateObject, of type <see cref="object"/>
				/// </summary>
				public static readonly global::Microsoft.Maui.Controls.BindableProperty PrivateObjectProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("PrivateObject", typeof(object), typeof(Container), default);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				static partial object? GetPrivateObject(global::Microsoft.Maui.Controls.BindableObject target) => target.GetValue(PrivateObjectProperty);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				static void SetPrivateObject(global::Microsoft.Maui.Controls.BindableObject target, object? value) => target.SetValue(PrivateObjectProperty, value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnTextSampleChanging(global::Microsoft.Maui.Controls.Label target, string? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnTextSampleChanging(global::Microsoft.Maui.Controls.Label target, string? oldValue, string? newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnTextSampleChanged(global::Microsoft.Maui.Controls.Label target, string? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnTextSampleChanged(global::Microsoft.Maui.Controls.Label target, string? oldValue, string? newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnNumSampleChanging(global::Microsoft.Maui.Controls.BindableObject target, int? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnNumSampleChanging(global::Microsoft.Maui.Controls.BindableObject target, int? oldValue, int? newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnNumSampleChanged(global::Microsoft.Maui.Controls.BindableObject target, int? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnNumSampleChanged(global::Microsoft.Maui.Controls.BindableObject target, int? oldValue, int? newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnPrivateObjectChanging(global::Microsoft.Maui.Controls.BindableObject target, object? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnPrivateObjectChanging(global::Microsoft.Maui.Controls.BindableObject target, object? oldValue, object? newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnPrivateObjectChanged(global::Microsoft.Maui.Controls.BindableObject target, object? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnPrivateObjectChanged(global::Microsoft.Maui.Controls.BindableObject target, object? oldValue, object? newValue);
			}
			""";

		VerifyGenerateSources(source, [new AttachedPropertyGenerator()], ("SimpleAttachedProps.Container.g.cs", result));
	}

	[TestCase]
	public void AttachedPropertyWithDefaults()
	{
		var source = """
			using Microsoft.Maui.Controls;
			using Dwarf.Toolkit.Maui;

			namespace AttachedWithDefaults;

			static partial class Container
			{
				[AttachedProperty(DefaultValue="Привет, Вася!", DefaultBindingMode=BindingModeDef.OneWayToSource))]
				public static partial string? GetTextSample(Label target);
				[AttachedProperty(DefaultValueExpression="3.14159")]
				internal static partial float? GetFloatNum(BindableObject target);
				
				static void OnTextSampleChanging(Label target, string? value);
				static void OnFloatNumChanged(BindableObject target, float? value);
				static void OnFloatNumChanged(BindableObject target, float? oldValue, float? newValue);
			}
			""";

		var result = """
			// <auto-generated/>
			#pragma warning disable
			#nullable enable
			namespace AttachedWithDefaults;
			/// <inheritdoc/>
			partial class Container
			{
				/// <summary>
				/// Creates an attached property named TextSample, of type <see cref="string"/>
				/// </summary>
				public static readonly global::Microsoft.Maui.Controls.BindableProperty TextSampleProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("TextSample", typeof(string), typeof(Container), "Привет, Вася!", defaultBindingMode: (global::Microsoft.Maui.Controls.BindingMode)3, propertyChanging: __TextSample_Changing);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public static partial string? GetTextSample(global::Microsoft.Maui.Controls.Label target) => (string)target.GetValue(TextSampleProperty);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public static void SetTextSample(global::Microsoft.Maui.Controls.Label target, string? value) => target.SetValue(TextSampleProperty, value);
				/// <summary>
				/// Creates an attached property named FloatNum, of type <see cref="float?"/>
				/// </summary>
				public static readonly global::Microsoft.Maui.Controls.BindableProperty FloatNumProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("FloatNum", typeof(float?), typeof(Container), 3.14159, propertyChanged: __FloatNum_Changed);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal static partial float? GetFloatNum(global::Microsoft.Maui.Controls.BindableObject target) => (float?)target.GetValue(FloatNumProperty);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal static void SetFloatNum(global::Microsoft.Maui.Controls.BindableObject target, float? value) => target.SetValue(FloatNumProperty, value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnTextSampleChanging(global::Microsoft.Maui.Controls.Label target, string? oldValue, string? newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __TextSample_Changing(global::Microsoft.Maui.Controls.BindableObject bindable, object oldValue, object newValue)
				{
					OnTextSampleChanging((global::Microsoft.Maui.Controls.Label)bindable, (string)newValue);
					OnTextSampleChanging((global::Microsoft.Maui.Controls.Label)bindable, (string)oldValue, (string)newValue);
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnTextSampleChanged(global::Microsoft.Maui.Controls.Label target, string? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnTextSampleChanged(global::Microsoft.Maui.Controls.Label target, string? oldValue, string? newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnFloatNumChanging(global::Microsoft.Maui.Controls.BindableObject target, float? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnFloatNumChanging(global::Microsoft.Maui.Controls.BindableObject target, float? oldValue, float? newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __FloatNum_Changed(global::Microsoft.Maui.Controls.BindableObject bindable, object oldValue, object newValue)
				{
					OnFloatNumChanged(bindable, (float?)newValue);
					OnFloatNumChanged(bindable, (float?)oldValue, (float?)newValue);
				}
			}
			""";

		VerifyGenerateSources(source, [new AttachedPropertyGenerator()], ("AttachedWithDefaults.Container.g.cs", result));
	}

	[TestCase]
	public void AttachedPropertyWithValidation()
	{
		var source = """
			using Microsoft.Maui.Controls;
			using Dwarf.Toolkit.Maui;

			namespace AttachedWithValidation;

			static partial class Container
			{
				[AttachedProperty(ValidateMethod="TextSampleValidation")]
				public static partial string? GetTextSample(Label target);
			
				[AttachedProperty(ValidateMethod="FloatNumValidation")]
				internal static partial float? GetFloatNum(BindableObject target);
			
				static void OnTextSampleChanging(Label target, string? oldValue, string? newValue);
				static void OnTextSampleChanging(Label target, string? value);
				static void OnTextSampleChanged(Label target, string? oldValue, string? newValue);
				static void OnTextSampleChanged(Label target, string? value);
				
				static void OnFloatNumChanging(BindableObject target, float? value);
				static void OnFloatNumChanging(BindableObject target, float? oldValue, float? newValue);
				static void OnFloatNumChanged(BindableObject target, float? value);
				static void OnFloatNumChanged(BindableObject target, float? oldValue, float? newValue);

				static bool FloatNumValidation(BindableObject target, float? value);
			}
			""";

		var result = """
			// <auto-generated/>
			#pragma warning disable
			#nullable enable
			namespace AttachedWithValidation;
			/// <inheritdoc/>
			partial class Container
			{
				/// <summary>
				/// Creates an attached property named TextSample, of type <see cref="string"/>
				/// </summary>
				public static readonly global::Microsoft.Maui.Controls.BindableProperty TextSampleProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("TextSample", typeof(string), typeof(Container), default, propertyChanging: __TextSample_Changing, propertyChanged: __TextSample_Changed, validateValue: __TextSample_Validate);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public static partial string? GetTextSample(global::Microsoft.Maui.Controls.Label target) => (string)target.GetValue(TextSampleProperty);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public static void SetTextSample(global::Microsoft.Maui.Controls.Label target, string? value) => target.SetValue(TextSampleProperty, value);
				/// <summary>
				/// Creates an attached property named FloatNum, of type <see cref="float?"/>
				/// </summary>
				public static readonly global::Microsoft.Maui.Controls.BindableProperty FloatNumProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("FloatNum", typeof(float?), typeof(Container), default, propertyChanging: __FloatNum_Changing, propertyChanged: __FloatNum_Changed, validateValue: __FloatNum_Validate);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal static partial float? GetFloatNum(global::Microsoft.Maui.Controls.BindableObject target) => (float?)target.GetValue(FloatNumProperty);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal static void SetFloatNum(global::Microsoft.Maui.Controls.BindableObject target, float? value) => target.SetValue(FloatNumProperty, value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __TextSample_Changing(global::Microsoft.Maui.Controls.BindableObject bindable, object oldValue, object newValue)
				{
					OnTextSampleChanging((global::Microsoft.Maui.Controls.Label)bindable, (string)newValue);
					OnTextSampleChanging((global::Microsoft.Maui.Controls.Label)bindable, (string)oldValue, (string)newValue);
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __TextSample_Changed(global::Microsoft.Maui.Controls.BindableObject bindable, object oldValue, object newValue)
				{
					OnTextSampleChanged((global::Microsoft.Maui.Controls.Label)bindable, (string)newValue);
					OnTextSampleChanged((global::Microsoft.Maui.Controls.Label)bindable, (string)oldValue, (string)newValue);
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				private static partial bool TextSampleValidation(global::Microsoft.Maui.Controls.Label target, string? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static bool __TextSample_Validate(global::Microsoft.Maui.Controls.BindableObject bindable, object value) => TextSampleValidation((global::Microsoft.Maui.Controls.Label)bindable, (string)value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __FloatNum_Changing(global::Microsoft.Maui.Controls.BindableObject bindable, object oldValue, object newValue)
				{
					OnFloatNumChanging(bindable, (float?)newValue);
					OnFloatNumChanging(bindable, (float?)oldValue, (float?)newValue);
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __FloatNum_Changed(global::Microsoft.Maui.Controls.BindableObject bindable, object oldValue, object newValue)
				{
					OnFloatNumChanged(bindable, (float?)newValue);
					OnFloatNumChanged(bindable, (float?)oldValue, (float?)newValue);
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static bool __FloatNum_Validate(global::Microsoft.Maui.Controls.BindableObject bindable, object value) => FloatNumValidation(bindable, (float?)value);
			}
			""";

		VerifyGenerateSources(source, [new AttachedPropertyGenerator()], ("AttachedWithValidation.Container.g.cs", result));
	}

	[TestCase]
	public void AttachedPropertyWithCoerce()
	{
		var source = """
			using Microsoft.Maui.Controls;
			using Dwarf.Toolkit.Maui;

			namespace AttachedWithCoerce;

			static partial class Container
			{
				[AttachedProperty(CoerceMethod="TextSampleCoerce")]
				public static partial string? GetTextSample(Label target);
			
				[AttachedProperty(CoerceMethod="CustomObjectCoerce")]
				internal static partial object GetCustomObject(BindableObject target);
			
				static void OnTextSampleChanging(Label target, string? oldValue, string? newValue);
				static void OnTextSampleChanging(Label target, string? value);
				
				static void OnCustomObjectChanged(BindableObject target, object value);
				static void OnCustomObjectChanged(BindableObject target, object oldValue, object newValue);

				static string? TextSampleCoerce(BindableObject target, string? value);
			}
			""";

		var result = """
			// <auto-generated/>
			#pragma warning disable
			#nullable enable
			namespace AttachedWithCoerce;
			/// <inheritdoc/>
			partial class Container
			{
				/// <summary>
				/// Creates an attached property named TextSample, of type <see cref="string"/>
				/// </summary>
				public static readonly global::Microsoft.Maui.Controls.BindableProperty TextSampleProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("TextSample", typeof(string), typeof(Container), default, propertyChanging: __TextSample_Changing, coerceValue: __TextSample_Coerce);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public static partial string? GetTextSample(global::Microsoft.Maui.Controls.Label target) => (string)target.GetValue(TextSampleProperty);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public static void SetTextSample(global::Microsoft.Maui.Controls.Label target, string? value) => target.SetValue(TextSampleProperty, value);
				/// <summary>
				/// Creates an attached property named CustomObject, of type <see cref="object"/>
				/// </summary>
				public static readonly global::Microsoft.Maui.Controls.BindableProperty CustomObjectProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("CustomObject", typeof(object), typeof(Container), default, propertyChanged: __CustomObject_Changed, coerceValue: __CustomObject_Coerce);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal static partial object GetCustomObject(global::Microsoft.Maui.Controls.BindableObject target) => target.GetValue(CustomObjectProperty);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal static void SetCustomObject(global::Microsoft.Maui.Controls.BindableObject target, object value) => target.SetValue(CustomObjectProperty, value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __TextSample_Changing(global::Microsoft.Maui.Controls.BindableObject bindable, object oldValue, object newValue)
				{
					OnTextSampleChanging((global::Microsoft.Maui.Controls.Label)bindable, (string)newValue);
					OnTextSampleChanging((global::Microsoft.Maui.Controls.Label)bindable, (string)oldValue, (string)newValue);
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnTextSampleChanged(global::Microsoft.Maui.Controls.Label target, string? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnTextSampleChanged(global::Microsoft.Maui.Controls.Label target, string? oldValue, string? newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				private static partial string? TextSampleCoerce(global::Microsoft.Maui.Controls.Label target, string? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static object __TextSample_Coerce(global::Microsoft.Maui.Controls.BindableObject bindable, object value) => TextSampleCoerce((global::Microsoft.Maui.Controls.Label)bindable, (string)value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnCustomObjectChanging(global::Microsoft.Maui.Controls.BindableObject target, object value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				static partial void OnCustomObjectChanging(global::Microsoft.Maui.Controls.BindableObject target, object oldValue, object newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __CustomObject_Changed(global::Microsoft.Maui.Controls.BindableObject bindable, object oldValue, object newValue)
				{
					OnCustomObjectChanged(bindable, newValue);
					OnCustomObjectChanged(bindable, oldValue, newValue);
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				private static partial object CustomObjectCoerce(global::Microsoft.Maui.Controls.BindableObject target, object value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static object __CustomObject_Coerce(global::Microsoft.Maui.Controls.BindableObject bindable, object value) => CustomObjectCoerce(bindable, value);
			}
			""";

		VerifyGenerateSources(source, [new AttachedPropertyGenerator()], ("AttachedWithCoerce.Container.g.cs", result));
	}
}