namespace Dwarf.Toolkit.Tests.SourceGenerators;

using Dwarf.Toolkit.Maui.SourceGenerators;
using NUnit.Framework;
using static CodegenTestHelpers;

[TestFixture]
internal sealed class AttachedPropertyTest
{
	[TestCase]
	public void SimpleAttachedProperty()
	{
		var source = """
			using Microsoft.Maui.Controls;
			using Dwarf.Toolkit.Maui;

			namespace SingleSimpleProp;

			partial static class Container
			{
				[AttachedProperty]
				public static partial string? GetTextSample(Label target);
			}
			""";

		var result = """
			// <auto-generated/>
			#pragma warning disable
			#nullable enable
			namespace SingleSimpleProp;
			/// <inheritdoc/>
			partial class Container
			{
				public static readonly BindableProperty MyPropProperty = BindableProperty.Create(nameof(MyProp), typeof(string), typeof(Container), propertyChanged: __MyProp_Changed);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				partial string? MyProp { get => (string)GetValue(MyPropProperty); set => SetValue(MyPropProperty, value); }

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnMyPropChanging(string? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnMyPropChanging(string? oldValue, string? newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnMyPropChanged(string? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnMyPropChanged(string? oldValue, string? newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __MyProp_Changed(BindableObject bindable, object oldValue, object newValue)
				{
					var _instance = (Container)bindable;
					_instance.OnMyPropChanged((string)newValue);
					_instance.OnMyPropChanged((string)oldValue, (string)newValue);
				}
			}
			""";

		VerifyGenerateSources(source, [new BindablePropertyGenerator()], ("SingleSimpleProp.Container.g.cs", result));
	}
}