using Dwarf.Toolkit.Maui.SourceGenerators;
using NUnit.Framework;

namespace Dwarf.Toolkit.Tests.SourceGenerators;
using static CodegenTestHelpers;

[TestFixture]
internal class BindablePropertyTest
{
	[TestCase]
	public void SimpleBindableProperty()
	{
		var source = """
			using Microsoft.Maui.Controls;
			using Dwarf.Toolkit.Maui;

			namespace SingleSimpleProp;

			partial class Container : BindableObject
			{
				[BindableProperty]
				partial string? MyProp { get; set; }
	
				partial void OnMyPropChanged(string val) {}
			}
			""";

		var result = """
			// <auto-generated/>
			#pragma warning disable
			#nullable enable
			namespace SingleSimpleProp;
			/// <inheritdoc/>
			partial class Container
			{
				/// <summary>
				/// Creates a bindable property named MyProp, of type <see cref="string"/>
				/// </summary>
				public static readonly BindableProperty MyPropProperty = BindableProperty.Create(nameof(MyProp), typeof(string), typeof(Container), propertyChanged: __MyProp_Changed);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				partial string? MyProp { get => (string)GetValue(MyPropProperty); set => SetValue(MyPropProperty, value); }

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnMyPropChanging(string? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnMyPropChanging(string? oldValue, string? newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnMyPropChanged(string? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnMyPropChanged(string? oldValue, string? newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __MyProp_Changed(BindableObject bindable, object oldValue, object newValue)
				{
					var _instance = (Container)bindable;
					_instance.OnMyPropChanged((string)newValue);
					_instance.OnMyPropChanged((string)oldValue, (string)newValue);
				}
			}
			""";

		VerifyGenerateSources(source, [new BindablePropertyGenerator()], ("SingleSimpleProp.Container.g.cs", result));
	}

	[TestCase]
	public void MultiAccessorsBindableProperties()
	{
		var source = """
			using Microsoft.Maui.Controls;
			using Dwarf.Toolkit.Maui;

			namespace MultiAccessorsProps;

			partial class Container : BindableObject
			{
				[BindableProperty]
				public partial string TextProp { get; set; }

				[BindableProperty]
				internal partial int? NumProp { get; set; }
			}
			""";

		var result = """
			// <auto-generated/>
			#pragma warning disable
			#nullable enable
			namespace MultiAccessorsProps;
			/// <inheritdoc/>
			partial class Container
			{
				/// <summary>
				/// Creates a bindable property named TextProp, of type <see cref="string"/>
				/// </summary>
				public static readonly BindableProperty TextPropProperty = BindableProperty.Create(nameof(TextProp), typeof(string), typeof(Container));
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public partial string TextProp { get => (string)GetValue(TextPropProperty); set => SetValue(TextPropProperty, value); }
			
				/// <summary>
				/// Creates a bindable property named NumProp, of type <see cref="int?"/>
				/// </summary>
				public static readonly BindableProperty NumPropProperty = BindableProperty.Create(nameof(NumProp), typeof(int?), typeof(Container));
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal partial int? NumProp { get => (int?)GetValue(NumPropProperty); set => SetValue(NumPropProperty, value); }
			
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnTextPropChanging(string value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnTextPropChanging(string oldValue, string newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnTextPropChanged(string value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnTextPropChanged(string oldValue, string newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnNumPropChanging(int? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnNumPropChanging(int? oldValue, int? newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnNumPropChanged(int? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnNumPropChanged(int? oldValue, int? newValue);
			}
			""";

		VerifyGenerateSources(source, [new BindablePropertyGenerator()], ("MultiAccessorsProps.Container.g.cs", result));
	}

	[TestCase]
	public void BindablePropertiesWithDefaultValue()
	{
		var source = """
			using Microsoft.Maui.Controls;
			using Dwarf.Toolkit.Maui;

			namespace WithDefaultValue;

			partial class Container : BindableObject
			{
				[BindableProperty(DefaultValue="Привет, Вася!", DefaultBindingMode=BindingModeDef.OneWayToSource)]
				public partial string TextProp { get; set; }

				[BindableProperty(DefaultValue=3.14159f)]
				public partial float FloatProp { get; set; }
			}
			""";

		var result = """
			// <auto-generated/>
			#pragma warning disable
			#nullable enable
			namespace WithDefaultValue;
			/// <inheritdoc/>
			partial class Container
			{
				/// <summary>
				/// Creates a bindable property named TextProp, of type <see cref="string"/>
				/// </summary>
				public static readonly BindableProperty TextPropProperty = BindableProperty.Create(nameof(TextProp), typeof(string), typeof(Container), defaultValue: "Привет, Вася!", defaultBindingMode: (global::Microsoft.Maui.Controls.BindingMode)3);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public partial string TextProp { get => (string)GetValue(TextPropProperty); set => SetValue(TextPropProperty, value); }
			
				/// <summary>
				/// Creates a bindable property named FloatProp, of type <see cref="float"/>
				/// </summary>
				public static readonly BindableProperty FloatPropProperty = BindableProperty.Create(nameof(FloatProp), typeof(float), typeof(Container), defaultValue: 3.14159F);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public partial float FloatProp { get => (float)GetValue(FloatPropProperty); set => SetValue(FloatPropProperty, value); }

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnTextPropChanging(string value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnTextPropChanging(string oldValue, string newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnTextPropChanged(string value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnTextPropChanged(string oldValue, string newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnFloatPropChanging(float value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnFloatPropChanging(float oldValue, float newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnFloatPropChanged(float value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnFloatPropChanged(float oldValue, float newValue);
			}
			""";

		VerifyGenerateSources(source, [new BindablePropertyGenerator()], ("WithDefaultValue.Container.g.cs", result));
	}

	[TestCase]
	public void BindablePropertiesWithDefaultValueExpression()
	{
		var source = """
			using Microsoft.Maui.Controls;
			using Dwarf.Toolkit.Maui;

			namespace WithDefaultValueExpression;

			partial class Container : BindableObject
			{
				[BindableProperty(DefaultValueExpression="DateTime.Now")]
				public partial DateTime DateTimeProp { get; set; }

				[BindableProperty(DefaultValueExpression="3.14159")]
				public partial float FloatProp { get; set; }
			}
			""";

		var result = """
			// <auto-generated/>
			#pragma warning disable
			#nullable enable
			namespace WithDefaultValueExpression;
			/// <inheritdoc/>
			partial class Container
			{
				/// <summary>
				/// Creates a bindable property named DateTimeProp, of type <see cref="DateTime"/>
				/// </summary>
				public static readonly BindableProperty DateTimePropProperty = BindableProperty.Create(nameof(DateTimeProp), typeof(DateTime), typeof(Container), defaultValue: DateTime.Now);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public partial DateTime DateTimeProp { get => (DateTime)GetValue(DateTimePropProperty); set => SetValue(DateTimePropProperty, value); }
			
				/// <summary>
				/// Creates a bindable property named FloatProp, of type <see cref="float"/>
				/// </summary>
				public static readonly BindableProperty FloatPropProperty = BindableProperty.Create(nameof(FloatProp), typeof(float), typeof(Container), defaultValue: 3.14159);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public partial float FloatProp { get => (float)GetValue(FloatPropProperty); set => SetValue(FloatPropProperty, value); }

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnDateTimePropChanging(DateTime value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnDateTimePropChanging(DateTime oldValue, DateTime newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnDateTimePropChanged(DateTime value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnDateTimePropChanged(DateTime oldValue, DateTime newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnFloatPropChanging(float value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnFloatPropChanging(float oldValue, float newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnFloatPropChanged(float value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				partial void OnFloatPropChanged(float oldValue, float newValue);
			}
			""";

		VerifyGenerateSources(source, [new BindablePropertyGenerator()], ("WithDefaultValueExpression.Container.g.cs", result));
	}

	[TestCase]
	public void BindablePropertyWithValidation()
	{
		var source = """
			using Microsoft.Maui.Controls;
			using Dwarf.Toolkit.Maui;

			namespace WithValidation;

			partial class Container : BindableObject
			{
				[BindableProperty(ValidateMethod="MyPropValidation")]
				partial string MyProp { get; set; }
	
				void OnMyPropChanged(string val) {}
				void OnMyPropChanged(string v1, string v2) {}
				void OnMyPropChanging(string val) {}
				void OnMyPropChanging(string v1, string v2) {}
			}
			""";

		var result = """
			// <auto-generated/>
			#pragma warning disable
			#nullable enable
			namespace WithValidation;
			/// <inheritdoc/>
			partial class Container
			{
				/// <summary>
				/// Creates a bindable property named MyProp, of type <see cref="string"/>
				/// </summary>
				public static readonly BindableProperty MyPropProperty = BindableProperty.Create(nameof(MyProp), typeof(string), typeof(Container), propertyChanging: __MyProp_Changing, propertyChanged: __MyProp_Changed, validateValue: __MyProp_Validate);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				partial string MyProp { get => (string)GetValue(MyPropProperty); set => SetValue(MyPropProperty, value); }

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __MyProp_Changing(BindableObject bindable, object oldValue, object newValue)
				{
					var _instance = (Container)bindable;
					_instance.OnMyPropChanging((string)newValue);
					_instance.OnMyPropChanging((string)oldValue, (string)newValue);
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __MyProp_Changed(BindableObject bindable, object oldValue, object newValue)
				{
					var _instance = (Container)bindable;
					_instance.OnMyPropChanged((string)newValue);
					_instance.OnMyPropChanged((string)oldValue, (string)newValue);
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				private partial bool MyPropValidation(string value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static bool __MyProp_Validate(BindableObject bindable, object value)
				{
					var _instance = (Container)bindable;
					return _instance.MyPropValidation((string)value);
				}
			}
			""";

		VerifyGenerateSources(source, [new BindablePropertyGenerator()], ("WithValidation.Container.g.cs", result));
	}

	[TestCase]
	public void BindablePropertyWithValidationWithoutPartial()
	{
		var source = """
			using Microsoft.Maui.Controls;
			using Dwarf.Toolkit.Maui;

			namespace WithValidationWithoutPartial;

			partial class Container : BindableObject
			{
				[BindableProperty(ValidateMethod="MyPropValidation")]
				partial string MyProp { get; set; }
	
				void OnMyPropChanged(string val) {}
				void OnMyPropChanged(string v1, string v2) {}
				void OnMyPropChanging(string val) {}
				void OnMyPropChanging(string v1, string v2) {}

				bool MyPropValidation(string val) => return true;
			}
			""";

		var result = """
			// <auto-generated/>
			#pragma warning disable
			#nullable enable
			namespace WithValidationWithoutPartial;
			/// <inheritdoc/>
			partial class Container
			{
				/// <summary>
				/// Creates a bindable property named MyProp, of type <see cref="string"/>
				/// </summary>
				public static readonly BindableProperty MyPropProperty = BindableProperty.Create(nameof(MyProp), typeof(string), typeof(Container), propertyChanging: __MyProp_Changing, propertyChanged: __MyProp_Changed, validateValue: __MyProp_Validate);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				partial string MyProp { get => (string)GetValue(MyPropProperty); set => SetValue(MyPropProperty, value); }

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __MyProp_Changing(BindableObject bindable, object oldValue, object newValue)
				{
					var _instance = (Container)bindable;
					_instance.OnMyPropChanging((string)newValue);
					_instance.OnMyPropChanging((string)oldValue, (string)newValue);
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __MyProp_Changed(BindableObject bindable, object oldValue, object newValue)
				{
					var _instance = (Container)bindable;
					_instance.OnMyPropChanged((string)newValue);
					_instance.OnMyPropChanged((string)oldValue, (string)newValue);
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static bool __MyProp_Validate(BindableObject bindable, object value)
				{
					var _instance = (Container)bindable;
					return _instance.MyPropValidation((string)value);
				}
			}
			""";

		VerifyGenerateSources(source, [new BindablePropertyGenerator()], ("WithValidationWithoutPartial.Container.g.cs", result));
	}

	[TestCase]
	public void BindablePropertyWithCoerce()
	{
		var source = """
			using Microsoft.Maui.Controls;
			using Dwarf.Toolkit.Maui;

			namespace WithCoerce;

			partial class Container : BindableObject
			{
				[BindableProperty(CoerceMethod="MyPropCoerce")]
				partial string MyProp { get; set; }
	
				[BindableProperty(CoerceMethod="MyProp2Coerce")]
				partial string MyProp2 { get; set; }

				void OnMyPropChanged(string val) {}
				void OnMyPropChanged(string v1, string v2) {}
				void OnMyPropChanging(string val) {}
				void OnMyPropChanging(string v1, string v2) {}

				void OnMyProp2Changed(string val) {}
				void OnMyProp2Changed(string v1, string v2) {}
				void OnMyProp2Changing(string val) {}
				void OnMyProp2Changing(string v1, string v2) {}
			
				string MyPropCoerce(string val) => return val;
			}
			""";

		var result = """
			// <auto-generated/>
			#pragma warning disable
			#nullable enable
			namespace WithCoerce;
			/// <inheritdoc/>
			partial class Container
			{
				/// <summary>
				/// Creates a bindable property named MyProp, of type <see cref="string"/>
				/// </summary>
				public static readonly BindableProperty MyPropProperty = BindableProperty.Create(nameof(MyProp), typeof(string), typeof(Container), propertyChanging: __MyProp_Changing, propertyChanged: __MyProp_Changed, coerceValue: __MyProp_Coerce);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				partial string MyProp { get => (string)GetValue(MyPropProperty); set => SetValue(MyPropProperty, value); }

				/// <summary>
				/// Creates a bindable property named MyProp2, of type <see cref="string"/>
				/// </summary>
				public static readonly BindableProperty MyProp2Property = BindableProperty.Create(nameof(MyProp2), typeof(string), typeof(Container), propertyChanging: __MyProp2_Changing, propertyChanged: __MyProp2_Changed, coerceValue: __MyProp2_Coerce);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				partial string MyProp2 { get => (string)GetValue(MyProp2Property); set => SetValue(MyProp2Property, value); }
			
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __MyProp_Changing(BindableObject bindable, object oldValue, object newValue)
				{
					var _instance = (Container)bindable;
					_instance.OnMyPropChanging((string)newValue);
					_instance.OnMyPropChanging((string)oldValue, (string)newValue);
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __MyProp_Changed(BindableObject bindable, object oldValue, object newValue)
				{
					var _instance = (Container)bindable;
					_instance.OnMyPropChanged((string)newValue);
					_instance.OnMyPropChanged((string)oldValue, (string)newValue);
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static object __MyProp_Coerce(BindableObject bindable, object value)
				{
					var _instance = (Container)bindable;
					return _instance.MyPropCoerce((string)value);
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __MyProp2_Changing(BindableObject bindable, object oldValue, object newValue)
				{
					var _instance = (Container)bindable;
					_instance.OnMyProp2Changing((string)newValue);
					_instance.OnMyProp2Changing((string)oldValue, (string)newValue);
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static void __MyProp2_Changed(BindableObject bindable, object oldValue, object newValue)
				{
					var _instance = (Container)bindable;
					_instance.OnMyProp2Changed((string)newValue);
					_instance.OnMyProp2Changed((string)oldValue, (string)newValue);
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				private partial string MyProp2Coerce(string value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				static object __MyProp2_Coerce(BindableObject bindable, object value)
				{
					var _instance = (Container)bindable;
					return _instance.MyProp2Coerce((string)value);
				}
			}
			""";

		VerifyGenerateSources(source, [new BindablePropertyGenerator()], ("WithCoerce.Container.g.cs", result));
	}
}