using Dwarf.Toolkit.Maui.SourceGenerators;
using NUnit.Framework;

namespace Dwarf.Toolkit.Tests.SourceGenerators;

[TestFixture]
internal partial class CodegenTest
{
	[TestCase]
	public void SimpleBindableProperty()
	{
		var source = """
			using Microsoft.Maui.Controls;
			using Dwarf.Toolkit.Maui;

			namespace SingleSimpleProp;

			partial class Container : BindableObject
			{
				[BindableProperty]
				partial string MyProp { get; set; }
	
				partial void OnMyPropChanged(string val) {}
			}
			""";

		var result = """
			// <auto-generated/>
			#pragma warning disable
			#nullable enable
			namespace SingleSimpleProp;
			/// <inheritdoc/>
			partial class Container
			{
				public static readonly BindableProperty MyPropProperty = BindableProperty.Create(nameof(MyProp), typeof(string), typeof(Container), propertyChanged: __MyProp_Changed);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				partial string MyProp { get => (string)GetValue(MyPropProperty); set => SetValue(MyPropProperty, value); }

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnMyPropChanging(string value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnMyPropChanging(string oldValue, string newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnMyPropChanged(string value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnMyPropChanged(string oldValue, string newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				static void __MyProp_Changed(BindableObject bindable, object oldValue, object newValue)
				{
					var _instance = (Container)bindable;
					_instance.OnMyPropChanged((string)newValue);
					_instance.OnMyPropChanged((string)oldValue, (string)newValue);
				}
			}
			""";

		VerifyGenerateSources(source, [new BindablePropertyGenerator()], ("SingleSimpleProp.Container.g.cs", result));
	}

	[TestCase]
	public void MultiAccessorsBindableProperties()
	{
		var source = """
			using Microsoft.Maui.Controls;
			using Dwarf.Toolkit.Maui;

			namespace MultiAccessorsProps;

			partial class Container : BindableObject
			{
				[BindableProperty]
				public partial string TextProp { get; set; }

				[BindableProperty]
				internal partial int? NumProp { get; set; }
			}
			""";

		var result = """
			// <auto-generated/>
			#pragma warning disable
			#nullable enable
			namespace MultiAccessorsProps;
			/// <inheritdoc/>
			partial class Container
			{
				public static readonly BindableProperty TextPropProperty = BindableProperty.Create(nameof(TextProp), typeof(string), typeof(Container));
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public partial string TextProp { get => (string)GetValue(TextPropProperty); set => SetValue(TextPropProperty, value); }
			
				public static readonly BindableProperty NumPropProperty = BindableProperty.Create(nameof(NumProp), typeof(int?), typeof(Container));
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal partial int? NumProp { get => (int?)GetValue(NumPropProperty); set => SetValue(NumPropProperty, value); }
			
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnTextPropChanging(string value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnTextPropChanging(string oldValue, string newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnTextPropChanged(string value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnTextPropChanged(string oldValue, string newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnNumPropChanging(int? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnNumPropChanging(int? oldValue, int? newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnNumPropChanged(int? value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnNumPropChanged(int? oldValue, int? newValue);
			}
			""";

		VerifyGenerateSources(source, [new BindablePropertyGenerator()], ("MultiAccessorsProps.Container.g.cs", result));
	}

	[TestCase]
	public void BindablePropertiesWithDefaultValue()
	{
		var source = """
			using Microsoft.Maui.Controls;
			using Dwarf.Toolkit.Maui;

			namespace WithDefaultValue;

			partial class Container : BindableObject
			{
				[BindableProperty(DefaultValue="Привет, Вася!")]
				public partial string TextProp { get; set; }

				[BindableProperty(DefaultValue=3.14159f)]
				public partial float FloatProp { get; set; }
			}
			""";

		var result = """
			// <auto-generated/>
			#pragma warning disable
			#nullable enable
			namespace WithDefaultValue;
			/// <inheritdoc/>
			partial class Container
			{
				public static readonly BindableProperty TextPropProperty = BindableProperty.Create(nameof(TextProp), typeof(string), typeof(Container), defaultValue: "Привет, Вася!");
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public partial string TextProp { get => (string)GetValue(TextPropProperty); set => SetValue(TextPropProperty, value); }
			
				public static readonly BindableProperty FloatPropProperty = BindableProperty.Create(nameof(FloatProp), typeof(float), typeof(Container), defaultValue: 3.14159F);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public partial float FloatProp { get => (float)GetValue(FloatPropProperty); set => SetValue(FloatPropProperty, value); }

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnTextPropChanging(string value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnTextPropChanging(string oldValue, string newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnTextPropChanged(string value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnTextPropChanged(string oldValue, string newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnFloatPropChanging(float value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnFloatPropChanging(float oldValue, float newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnFloatPropChanged(float value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnFloatPropChanged(float oldValue, float newValue);
			}
			""";

		VerifyGenerateSources(source, [new BindablePropertyGenerator()], ("WithDefaultValue.Container.g.cs", result));
	}

	[TestCase]
	public void BindablePropertiesWithDefaultValueExpression()
	{
		var source = """
			using Microsoft.Maui.Controls;
			using Dwarf.Toolkit.Maui;

			namespace WithDefaultValueExpression;

			partial class Container : BindableObject
			{
				[BindableProperty(DefaultValueExpression="DateTime.Now")]
				public partial DateTime DateTimeProp { get; set; }

				[BindableProperty(DefaultValueExpression="3.14159")]
				public partial float FloatProp { get; set; }
			}
			""";

		var result = """
			// <auto-generated/>
			#pragma warning disable
			#nullable enable
			namespace WithDefaultValueExpression;
			/// <inheritdoc/>
			partial class Container
			{
				public static readonly BindableProperty DateTimePropProperty = BindableProperty.Create(nameof(DateTimeProp), typeof(DateTime), typeof(Container), defaultValue: DateTime.Now);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public partial DateTime DateTimeProp { get => (DateTime)GetValue(DateTimePropProperty); set => SetValue(DateTimePropProperty, value); }
			
				public static readonly BindableProperty FloatPropProperty = BindableProperty.Create(nameof(FloatProp), typeof(float), typeof(Container), defaultValue: 3.14159);
				/// <inheritdoc/>
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", <ASSEMBLY_VERSION>)]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				public partial float FloatProp { get => (float)GetValue(FloatPropProperty); set => SetValue(FloatPropProperty, value); }

				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnDateTimePropChanging(DateTime value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnDateTimePropChanging(DateTime oldValue, DateTime newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnDateTimePropChanged(DateTime value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnDateTimePropChanged(DateTime oldValue, DateTime newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnFloatPropChanging(float value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnFloatPropChanging(float oldValue, float newValue);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnFloatPropChanged(float value);
				[global::System.CodeDom.Compiler.GeneratedCode("Dwarf.Toolkit.Maui.SourceGenerators.BindablePropertyGenerator", "0.1.1.0")]
				partial void OnFloatPropChanged(float oldValue, float newValue);
			}
			""";

		VerifyGenerateSources(source, [new BindablePropertyGenerator()], ("WithDefaultValueExpression.Container.g.cs", result));
	}
}